staticSites:
  - name: happy-caravan
    repo: https://github.com/tmggl/happy-caravan2
    branch: main
    rootDir: .
    buildCommand: echo "No build step"
    publishPath: .
    pullRequestPreviewsEnabled: false
